### ISSUE TITLE
Premium Currency tab not rendering correctly.

### ISSUE THREAD

**Issue by aydjay** [Stickymaddness/Procurement#609]
While I was adding the new Silver Coins to the application I noticed that my currency tab was not being displayed correctly.

I have investigated it and in the JSon that is coming from the server when you are pulling from a currency stash it marks the x and y of an item (Currency in this case) as: x=2 and y=0.

There is a new json object at the bottom that shows the "CurrencyLayout" which has the exact location of each item. Illustrated below:

![image](https://cloud.githubusercontent.com/assets/9460838/16118069/34606d92-33cd-11e6-8a39-aaac067635fc.png)

In this case the Orb of alteration has x:9 and y:0 and then the currency layout has a slot for "9" with precise location x and y (Including the size)

Slot 28 looks to be the item crafting location.
![image](https://cloud.githubusercontent.com/assets/9460838/16118102/5f8d51f6-33cd-11e6-9456-5c0697a79074.png)

I will have a look to see if I can get everything to layout "Reasonably" otherwise as above these are my findings.

[My currency tab bin file](https://github.com/Stickymaddness/Procurement/files/318475/Prophecy-stash-0.txt)

**Comment by Stickymaddness** [comment]
This was addressed in your pull request  - reopen if that is not the case.

**Comment by aydjay** [comment]
Sadly I did not fix this in my PR. I had a look to see if it was straight forward to implement but I ran out of time for it.

It is still an issue. 

As far as I can tell there is a new view required to handle the currency tab information.

**Comment by Stickymaddness** [comment]
Right. 

I just tested, the currency tabs do load without it crashing, but it will need the new currency tab art to visually match up correctly.

**Comment by Stickymaddness** [comment]
I've updated the tab model to now include the tab type - Normal, Premium, Currency, Quad, etc.

A basic fix for quad tabs has been included in 1.11.0, but the control will need an overhaul to properly detect the type, set the correct tab background, and calculate the correct spacing for items.

**Comment by aydjay** [comment]
I've had another stab at this issue - i think i will have something ready to merge in the next couple of days.

**Comment by aydjay** [comment]
https://github.com/aydjay/Procurement/tree/currencyTab

**Comment by Stickymaddness** [comment]
Nice work, definitely throw up a PR when you're ready. One thing to keep in mind is that GGG have said the currency tab is going to be updated for the new orb types in the near future.

**Comment by aydjay** [comment]
Yes - I saw that after I had started....

Fortunately it's not going to be too hard to add to the work I've already done.
